### ISSUE TITLE
Carbon intensity of energy production figures compared to EEA, EPA numbers

### ISSUE THREAD

**Issue by sichen1234** [owid/energy-data#1]
Thank you so much for putting together this great database.  We're trying to use your numbers for an open source blockchain carbon accounting system.

Could you explain how some of the numbers here are different than what we found from the EPA and EEA.  For example, I'm looking at the carbon intensity of energy for India, Germany, and USA:
<img width="1595" alt="Screen Shot 2020-12-09 at 1 27 59 PM" src="https://user-images.githubusercontent.com/1706353/101691250-491f8180-3a23-11eb-84f3-32c756ca1c73.png">

This shows both Germany and USA at 0.21 kg/KWH of electricity.  

The EEA publishes a statistic for all the EU countries: https://www.eea.europa.eu/data-and-maps/daviz/co2-emission-intensity-5

For Germany it has 440.8 g/kWH in 2016.

The EPA publishes an EGRID database (https://www.epa.gov/sites/production/files/2020-01/egrid2018_all_files.zip) and for 2018, the total of all USA utilities was 1,985,972,374 tons CO2e for 4,168,365,243 MWH of total electricity generated, or about 0.476 kG/KWH.

Thank you.

**Comment by ethicalvats** [comment]
agree with @opentaps the discrepancy in data values makes it difficult to come up with a generalised system on carbon and emissions accounting. Great initiative though!

**Comment by edomt** [comment]
Hi @opentaps @ethicalvats 

In your example, you are comparing carbon intensity of _electricity_ from these other sources, to our carbon intensity of _total energy_ (which includes electricity, but also heat, transport and industrial processes). That is why the numbers are different.

We are hoping to get carbon intensity of electricity data in the future.

Edouard

**Comment by sichen1234** [comment]
OK thanks for clarifying that.
-----
Si Chen
Open Source Strategies, Inc.

Video: Fighting Climate Change with Blockchain and Open Source
<https://youtu.be/NgxNWXa_IjE>
