### ISSUE TITLE
order of columns in codebook is different from order in database

### ISSUE THREAD

**Issue by guggikofod** [owid/energy-data#21]
(brand new to both github and data sharing, apologies for any stupidities)

I have made a small project based on this energy data, and am still in the middle of the project phase.

I re-downloaded the database, and noted the order of columns had changed in the database. (updated 220810). in my view, the new column ordering is an improvement over the previous.

However, the order of columns in the codebook is still as before the update.

It might be helpful to order the column descriptions in the codebook following the order in the database.

**Comment by pabloarosado** [comment]
Thanks for your suggestion, @guggikofod! I have just pushed some changes so that the codebook column descriptions are aligned with the dataset columns.
