### ISSUE TITLE
oil_electricity

### ISSUE THREAD

**Issue by koonimaru** [owid/energy-data#29]
Hi,
The values in the oil_electricity columns are oddly low, compared to other *_electricity columns. Are they true values?
Here is the case of United States in 2021.
year                           2021.00
biofuel_electricity              54.25
coal_electricity                897.89
fossil_electricity             2512.45
gas_electricity                1579.36
hydro_electricity               246.47
low_carbon_electricity         1637.50
nuclear_electricity             778.19
oil_electricity                  35.20
other_renewable_electricity      70.22
solar_electricity               164.42
wind_electricity                378.20

**Comment by pabloarosado** [comment]
Hi @koonimaru, yes, that's the case, oil is not commonly used to produce electricity. [On Ember's website](https://ember-climate.org/data/data-tools/data-explorer/) (which is our main source of data for electricity) you can see the comparison (oil is included as "Other Fossil").
