### ISSUE TITLE
Contact 

### ISSUE THREAD

**Issue by Tobe2d** [owid/energy-data#31]
What will be the best way to contact you directly?

I have sent email to info@ourworldindata.org and I havent heard back for about 10 days.

Need to discuss Potential Partnership

**Comment by edomt** [comment]
Hi @Tobe2d 

Thank you for getting in touch. If you have written to info@ourworldindata.org, our team will be looking at your email over the next few days. If you don't receive any answer soon, please assume that we're not currently able to pursue this partnership.
