### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by ghost** [owid/energy-data#33]
Hi!
First of all, thank you for providing these data, they are being very useful for my project!
I noticed that for some of the countries, like for instance for Switzerland in the case of share of electricity generation that comes from oil (column CM in the excel file "owid-energy-data"), this data is missing until the year of 2000.
I was wondering why, since all the data for the years before 2000 for this country are available.
Thank you in advance.
Lyubov

**Comment by pabloarosado** [comment]
Hi @lyuba-marmotta, thanks for your feedback! For the indicator you mention, we rely on [Ember's yearly electricity data](https://ember-climate.org/data-catalogue/yearly-electricity-data/), which currently doesn't have data for Switzerland prior to the year 2000. Hopefully, they will increase their date range in a future release.
