### ISSUE TITLE
Indicators

### ISSUE THREAD

**Issue by msgoussi** [owid/energy-data#36]
Hi...
i realized that the population and biofuel_consumption of North America in 2021 is not equal to population of Canada/Mexico/United Sates combined. 
i really wish if you can add column to the codebook (method) explaining the method of calculation (is sum or weighted average by column xx) etc. This would help us to understand how to calculate aggregates for certain group of countries concerned.
please advise

**Comment by pabloarosado** [comment]
Hi @msgoussi good point, we should better document how we construct aggregates. To clarify this question to you, [on this page](https://ourworldindata.org/world-region-map-definitions) you can see how we (and other institutions) define their regions. North America includes not only Canada, United States and Mexico, but also countries in Central America. I hope that helps.

**Comment by msgoussi** [comment]
Hi. 
It is possible to download the country/continent (full database) in the 
![image](https://github.com/owid/energy-data/assets/18138496/a0583693-02d0-43c1-a45f-38dab346770f)
via github directly?

Thanks

**Comment by msgoussi** [comment]
Hi... there are many indicators ends with _change_twh. i am wondering how to calculate them. 
ie biofuel_cons_change_twh, what is the formula for producing this indicator (UK in 2022 is 4.603).
