### ISSUE TITLE
Fix values >100% for "Share of electricity production from coal"

### ISSUE THREAD

**Issue by bnjmacdonald** [owid/energy-data#7]
"Europe (other)" and "Other Asia & Pacific" have a value >100% for the variable "Share of electricity production from coal". I am not immediately sure what the source of the problem is. Further inspection needed.

**Comment by pabloarosado** [comment]
On the latest update using Ember global electricity and the European Electricity Review, these regions still had incorrect values of electricity share (percentages larger than 100%). We have removed the affected regions.
